### ISSUE TITLE
Need activity log

### ISSUE THREAD

**Issue by supasate** [youpin-city/youpin-api#134]
Keep log for displaying on activity log 
- [x] log of status changing (#142) 
- [x] log of metadata changing (#180)
- [x] log of progress updating (#180)
- [x] log of issue merging (#172)
