### ISSUE TITLE
Provide Summary API

### ISSUE THREAD

**Issue by supasate** [youpin-city/youpin-api#141]
Summary API is used for Dashboard to show a number of pins of each department in each status

Two routings will be created:
1.  Just a pure Restful resource for Summary CRUD API for each day. 
```
GET /summaries?organization=<organization_name>&start_date=2016-11-26&end_date=2016-11-28
{
    "total": 1,
    "limit": 5,
    "skip": 0,
    "data": [
        {
            "_id": "58394116a7e0c04c1ef645fc",
            "date": "2016-11-25",
            "organization": "58393507fef939356546404b",
            "updatedAt": "2016-11-26T08:57:59.998Z",
            "createdAt": "2016-11-26T08:57:59.995Z",
            "by_department": [
                {
                    "resolved": 1,
                    "processing": 3,
                    "assigned": 3,
                    "department": "58393507fef939356546404b",
                    "_id": "5839446ea7e0c04c1ef64604"
                }
            ]
        },
        {
            "_id": "58394116a7e0c04c1ef645fc",
            "date": "2016-11-26",
            "organization": "58393507fef939356546404b",
            "updatedAt": "2016-11-26T08:57:59.998Z",
            "createdAt": "2016-11-26T08:57:59.995Z",
            "by_department": [
                {
                    "resolved": 0,
                    "processing": 0,
                    "assigned": 1,
                    "department": "58393507fef939356546404b",
                    "_id": "5839446ea7e0c04c1ef64664"
                }
            ]
        }
    ]
}
```
But note that we will have a `trigger` param just for triggering it to re-calculate the summary numbers. 
```
GET /summaries?**trigger=true**&organization=<organization_name>&start=2016-11-25&end=2016-11-26
```

2. A special routing to sum up all specified daily summaries.
```
GET /conclude_summary?organization=<organization_name>&start=2016-09-01&end=2016-09-30

{
  start_date: 2016-09-01,
  end_date: 2016-09-30,
  total_unverified: 5,
  total_verified: 10,
  total_assigned: 8,
  total_processing: 14,
  total_resolved: 8,
  total_rejected: 5,
  by_department: [
    {
      department: <id of departmentA>,
      assigned: 5,
      processing: 10,
      resolved: 5 
    },
    {
      department: <id of departmentB>,
      assigned: 3,
      processing: 4,
      resolved: 3
     }
  ]
}
```
**[TODO]**
_Summary service_
- [x] Summary CRUD service +model  (/summaries) 
- [x] Add test: summary service
- [x] Add triggering parameter to calculate summary number

**Comment by parnurzeal** [comment]
seems to be very heavy when data grows. I wonder why we need starttime.
I think most of the usecase would be the total number until now.

**Comment by supasate** [comment]
The dashboard needs different time durations. I think the organization might need a report in different times (like by fiscal year, by quarter, etc.). Any idea?

![image](https://cloud.githubusercontent.com/assets/237753/20563935/43fbb6ee-b1bd-11e6-8ac9-57f254d71976.png)

**Comment by p16i** [comment]
I'm ok with the api.

**Comment by parnurzeal** [comment]
In addition, proposing another routing `GET /calculate_summary` to trigger a calculation for all above numbers at once. (which would get triggered periodically).

The underneath of`/summary` Restful service should do nothing except storing already-calculated numbers.

**Comment by p16i** [comment]
@supasate @parnurzeal I have made some adjustments for the returned result.
https://github.com/youpin-city/youpin-api/pull/155

**Comment by supasate** [comment]
Can we close this issue @parnurzeal ?

**Comment by parnurzeal** [comment]
Note that this is for summarizing state-action. 
We will have another API (/state-summaries) to get all up-to-date states for all departments in that organization. I will create another bug.

**Comment by supasate** [comment]
@parnurzeal Done yet???
